services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgis
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRESS_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  prefect-server:
    image: prefecthq/prefect:3.6-python3.11
    container_name: prefect-server
    working_dir: /opt/prefect
    command: prefect server start
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - "./services:/opt/prefect/services"
      - "./data:/opt/prefect/data"
      - prefect_internal:/root/.prefect
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgis_data:
  prefect_internal